### ISSUE TITLE
Minor Fixes to GUI

### ISSUE THREAD

**Issue by aditeyabaral** [aditeyabaral/PyDictionary#7]
The current GUI looks like this:
![image](https://user-images.githubusercontent.com/33230959/95154397-5ca63600-07af-11eb-8ca0-090e5ccc3565.png)

It would be great to add a few features/fixes - 

- [x] Remove the list numbers for results and instead show the results as cards (Similar to how Google Search on phones displays results as cards)
- [x] Fix for words not found in dictionary (Automatically handled in logic, needs to be handled in GUI) - 
![image](https://user-images.githubusercontent.com/33230959/95155148-223d9880-07b1-11eb-95d3-67126310a9f0.png)
- [x] An alternate (blue if possible) colour for the button that goes well with the background colour
- [x] A rounded edge box for the button, similar to the search box, if possible a flat or material design to match the search box

**Comment by xshadowlegendx** [comment]
hello, I am going to claim this

**Comment by aditeyabaral** [comment]
Sure, go ahead 👍

**Comment by xshadowlegendx** [comment]
hello should I also put `nltk.download("wordnet")` in `app.py` since it required to have wordnet downloaded before hand but we could add that line so that running the app will download it if it does not exists, I also fixed the overflow issue on the right side when there are long list of definition and also added `Flask-Bootstrap` dep to `requirements.txt` because the app uses it

**Comment by aditeyabaral** [comment]
@xshadowlegendx sure, add it in 👍

**Comment by xshadowlegendx** [comment]
thanks so I will send u pull request for you to review
